apps/todo/urls.py
from django.conf.urls import url
from .import views
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^$', login_required(views.TaskList.as_view()), name="task_list"),
    url(r'^task/new$', login_required(
        views.TaskCreate.as_view()), name='task_new'),
    url(r'^task/(?P<pk>\d+)/edit/$',
        login_required(views.TaskUpdate.as_view()), name="task_edit"),
    url(r'^task/(?P<pk>\d+)/delete/$',
        views.delete_task, name="task_delete"),
    url(r'^task/(?P<pk>\d+)/confirm/$',
        views.confirm_unconfirm_task, name="task_confirm"),
]

config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.todo.urls', namespace="todo")),
    url(r'^(?P<filename>(robots.txt)|(humans.txt))$',
        views.seo_files, name="seo_files"),
]

urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/', views.register, name="register"),
    url(r'^accounts/register$', RedirectView.as_view(
        url='/accounts/register/', permanent=True))

]

apps/todo/models.py
from datetime import date
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from . import managers

# Create your models here.


class Profile(models.Model):

    # Relations
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        related_name='profile',
        verbose_name='user',
        on_delete=models.CASCADE
    )

    # Attributes - Mandatory
    email_confirmed = models.BooleanField(default=False)
    # Attributes - Optional
    # Object Manager
    objects = managers.ProfileManager()

    # Custom Properties
    @property
    def task_count(self):
        return self.tasks.count()

    @property
    def username(self):
        # able to do 'profile.username' as opposed to 'profile.user.username'
        return self.user.username

    # Methods

    # Meta and String
    class Meta:
        verbose_name = "Profile"
        verbose_name_plural = "Profiles"

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_user_profile(sender, instance, created, **kwargs):
    #  automatically create profile whenever a new user is created
    if created:
        profile = Profile(user=instance)
        profile.save()


class Task(models.Model):

    # Relations
    user = models.ForeignKey(
        Profile,
        related_name='tasks',
        verbose_name='User'
    )

    PRIORITY = (
        (1, 'Low'),
        (2, 'Medium'),
        (3, 'High'),
    )

    # Attributes - Mandatory
    title = models.CharField(max_length=50, help_text="Name of this task")
    # description = models.TextField(help_text="task description")
    priority = models.IntegerField(choices=PRIORITY, default=1)
    is_complete = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    confirmed_by = models.ForeignKey(
        Profile,
        related_name='confirms',
        verbose_name='Approval',
        null=True
    )

    # Attributes - Optional
    due_date = models.DateField(
        null=True, blank=True, help_text="intended date of completion")
    completed_date = models.DateField(null=True, blank=True)

    # Object Manager
    objects = managers.ProjectManager()

    # Custom Properties
    @property
    def is_overdue(self):
        if self.due_date and date.today() > self.due_date:
            return True
        return False

    # Methods

    # Meta and String
    class Meta:
        verbose_name = "Task"
        verbose_name_plural = "Tasks"
        ordering = ("-created_at", "title")
        unique_together = ("user", "title")

    def __str__(self):
        return self.title

apps/todo/forms.py
import datetime
from django import forms
from .models import (Task)
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError


class SignUpForm(forms.ModelForm):

    class Meta:
        model = get_user_model()
        fields = ('username', 'password')


class CreateTaskForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(CreateTaskForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Task
        fields = ('title', 'priority', 'due_date', 'is_complete')

    def clean_due_date(self):
        if self.cleaned_data['due_date']:
            field = self.cleaned_data['due_date']
            if field < datetime.date.today():
                raise ValidationError('Invalid date - due date in past')
            return field

    def clean_title(self):
        data = self.cleaned_data['title']
        title_occurrence = Task.objects.filter(
            title__iexact=data.lower(), user=self.request.user.profile).count()
        is_create = self.instance.pk is None  # dont validate on update
        if is_create and title_occurrence > 0:
            raise ValidationError('You already have a task with this name')
        return data

    def save(self, commit=False):
        self.instance.user = self.request.user.profile
        self.instance.save()
        return self.instance

apps/todo/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import JsonResponse
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from .models import Task
from .forms import CreateTaskForm
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required


class TaskList(generic.ListView):
    model = Task
    paginate_by = 20


class TaskUpdate(generic.UpdateView):
    model = Task
    success_url = reverse_lazy('todo:task_list')
    form_class = CreateTaskForm

    def get_form_kwargs(self):
        kwargs = super(TaskUpdate, self).get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs


class TaskCreate(generic.CreateView):
    model = Task
    success_url = reverse_lazy('todo:task_list')
    form_class = CreateTaskForm
    template_name = 'todo/task_list.html'

    def get_form_kwargs(self):
        kwargs = super(TaskCreate, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(TaskCreate, self).get_context_data(**kwargs)
        context['task_list'] = Task.objects.all()[:20]
        return context


class TaskDelete(generic.DeleteView):
    model = Task
    success_url = reverse_lazy('todo:task_list')


@login_required()
def delete_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        if (request.user == task.user.user):
            task.delete()
        return redirect(reverse_lazy('todo:task_list'))
    return render(request, 'todo/confirm_task_delete.html', {"task": task})


@login_required()
@require_http_methods(['POST'])
def confirm_unconfirm_task(request, pk):
    data = {}
    task = None
    try:
        task = Task.objects.get(pk=pk)
        task.is_complete = not task.is_complete
        task.confirmed_by = request.user.profile
        task.save()
        status = 200
        data['message'] = 'Task confirmed successfully'
        data['confirmed_by'] = request.user.username
    except Task.DoesNotExist:
        status = 404
        data['message'] = 'Task not found'
    return JsonResponse(data, status=status)

config/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm


def seo_files(request, filename):
    return render(request, filename, {}, content_type="text/plain")


def register(request):
    form = UserCreationForm(request.POST or None)
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('todo:task_list')
    return render(request, 'registration/register.html', {'form': form})

apps/todo/templates/todo/confirm_task_delete.html
{% extends "base.html" %}


{% block content %}
  

<form method="post" action="{% url 'todo:task_delete' task.id %}" class="task-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Confirm deletion - "{{task.title}}"</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete this task?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal" 
      onclick="location.href ='/'">Back</button>
    <button type="submit" class="btn btn-danger">Delete task</button>
  </div>
</form>
{% endblock content %}

apps/todo/templates/todo/task_form.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row task-data" style="background: transparent">
            <div class="col col-md-8">
                <form method="POST" action="{% url 'todo:task_edit' task.id %}" class="form-inline">
                    {% csrf_token %}
                    <div class="row">

                        <div class="col-md-2 padding-2">
                            <label for="">{{form.title.label}}:</label>
                        </div>
                          <div class="col-md-10 padding-2">
                                {% for error in form.title.errors  %}
                                    <p style="color: red">{{error}}</p>
                                {% endfor %}
                                <input type="text" class="txt" placeholder="Title of task" 
                                    title="task title" name="title" value="{{form.title.value}}"
                                    style="padding: 10px" />
                          </div>
                          <div class="col-md-2 padding-2"><label for="">{{form.due_date.label}}:</label></div>
                          <div class="col-md-10 padding-2">
                            {% for error in form.due_date.errors  %}
                                <p style="color: red">{{error}}</p>
                            {% endfor %}
                              <input type="date" class="dates" title="due date" 
                                name="due_date" value="{{form.due_date.value|date:'Y-m-d'}}">
                          </div>
                          <div class="col-md-2 padding-2"><label for="">{{form.priority.label}}:</label></div>
                          <div class="col-md-10 padding-2">
                                {% for error in form.priority.errors  %}
                                    <p style="color: red">{{error}}</p>
                                {% endfor %}
                                {{form.priority}}
                          </div>
                    </div>
                    <div class="row">
                      <div class="col-md-2 padding-2"><label for="">Completed?:</label></div>
                          <div class="col-md-10 padding-2">
                            {% for error in form.is_complete.errors  %}
                                <p style="color: red">{{error}}</p>
                            {% endfor %}
                              {{form.is_complete}}
                          </div>
                    </div>
                    <input type="submit" value="Update" class="btn btn-success">
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

apps/todo/templates/todo/task_list.html
{% extends "base.html" %}

{% block js %}
    {% load staticfiles %}
    <script src='{% static "js/services/services.js" %}'></script>
    <script src='{% static "js/controllers/controllers.js" %}'></script>
{% endblock js %}

{% block content %}
    
 <div class="page-container"> 
  <a class="pull-right toggle-complete">Hide completed</a>
  <h2>All Tasks</h2>
  {% if is_paginated %}
  <div class="text-center">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
          <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>
  </div>
{% endif %}
  <ul class="todo-list">
    {% for task in task_list   %}
        <li class="list-item">
          {{task.title}}
          <span class="center-block text-small">{{task.user.username}}</span>
          <!-- <a href="#collapse-{{task.id}}" class="task-desc-toggle" data-toggle="collapse">
              Description
          </a> -->
          <div class="buttons">
            {% if task.is_complete %}
                <button class="bt bt-achieve bt-complete" 
                    data-toggle="tooltip" title="Confirmed by {{task.confirmed_by.username}}">
                    <span class="glyphicon glyphicon-ok task-complete" 
                    data-task-id="{{task.id}}" data-url="{% url 'todo:task_confirm' task.id %}"></span>
                </button>
                {% else %}
                <button class="bt bt-achieve">
                <img src="/static/img/spinner.svg" class="spinner">
                <span class="glyphicon glyphicon-ok task-confirm" 
                    data-task-id="{{task.id}}" data-url="{% url 'todo:task_confirm' task.id %}"></span>
                </button>
            {% endif %}
            {% if  task.user.user == request.user%}
              <button class="bt bt-achieve">
                <a href="{% url 'todo:task_edit' task.id %}"><span class="glyphicon glyphicon-edit"></span></a>
                </button>
              <button class="bt bt-delete">
                <a href="{% url 'todo:task_delete' task.id %}"><span class="glyphicon glyphicon-remove"></span></a>
                </button>
            {% endif %}
          </div>
            <div id="collapse-{{task.id}}" class="collapse">
                {{task.description}}
            </div>
        </li>
    {% empty %}
      <li class="list-item">No tasks for now! Click the button to add</li>
    {% endfor %}
  </ul>
  <div>
      <ul class="add-todo" {% if  not form.errors%} style="display: none"{% endif %}>
        <li>
            <form method="POST" action="{% url 'todo:task_new' %}">
                {% csrf_token %}
                {% for error in form.priority.errors  %}
                    <p style="color: red; background: #0f0a0a; max-width: 90%">{{error}}</p>
                {% endfor %}
                {% for error in form.due_date.errors  %}
                    <p style="color: red; background: #0f0a0a; max-width: 90%">{{error}}</p>
                {% endfor %}
                {% for error in form.title.errors  %}
                    <p style="color: red; background: #0f0a0a; max-width: 90%">{{error}}</p>
                {% endfor %}
                <div class="task-data">
                      <input type="text" class="txt" placeholder="Title of task" 
                        title="task title" name="title"/>
                      <input type="date" class="date" title="due date" name="due_date">
                      <select id="" class="sel" title="task priority" name="priority">
                          <option value="1">Low</option>
                          <option value="2">Medium</option>
                          <option value="3">High</option>
                      </select>
                      
                </div>
            </form>
        </li>
      </ul>

      <div class="float-button" data-toggle="tooltip" title="add new task">
        <span>
            <a class="content">
                <span class="glyphicon glyphicon-plus"></span>
            </a>
        </span>
    </div>
  </div>
</div>


{% endblock content %}

templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<html>
  {% load staticfiles %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}DjangList{% endblock title %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">

    <link href='//fonts.googleapis.com/css?family=Roboto:100,300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block css %}{% endblock css %}
  </head>

  <body>
    {% include "header.html" %}

    <div style="margin-top: 70px">
      {% block content %}
        
      {% endblock content %}
    </div>
    
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
    <script src="{% static 'js/app.js' %}"></script>
    {% block js %}{% endblock js %}
  </body>

</html>

templates/header.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">DjangList</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <form class="navbar-form navbar-right" role="form" action="{% url 'login' %}" method="POST">
        {% csrf_token %}
        {% if request.user.is_authenticated %}
          <span>{{request.user.username}}</span>
          <a href="{% url 'logout'%}">Logout</a>
        {% else %}
        <div class="form-group">
          <input type="text" placeholder="Username" class="form-control" name="username">
        </div>
        <div class="form-group">
          <input type="password" placeholder="Password" class="form-control" name="password">
        </div>
        <button type="submit" class="btn btn-success">Sign in</button>
        {% endif %}
      </form>
    </div><!--/.navbar-collapse -->
  </div>
</nav>   